### ISSUE TITLE
[Feature 7] User Discovery

### ISSUE THREAD

**Issue by Caconoutt** [CSC207-2022F-UofT/course-project-group-45-tut0201-ba3185#7]
The user discovery allows the user to get a list of other users based on one of the three algorithms 'NearByDiscovery', 'PreferenceDiscovery' and. 'SearchDiscovery'.

**Comment by Christina0313** [comment]
Expected Date:  Nov.10
Reviewer: Jennifer, Alyssa, Sunny, Eric
